spring.application.name=microservicesKafka
server.port=8081

eureka.client.restclient.enabled=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=defaultGroup
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Asaas - paymentService
asaas.api.url=https://sandbox.asaas.com/api/v3
asaas.api.key=$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjAzM2IzYjkwLWVlN2UtNDFjZC04Y2VkLTE4NWRiYmE5M2RhODo6JGFhY2hfMzJiYjBmYzYtOGY3Mi00NjQwLTlmZjQtZWM3OGQ0NDA5NWMy